add missing include
fix:
[ 63%] Building CXX object gui/CMakeFiles/gui.dir/gui_autogen/mocs_compilation.cpp.o
In file included from …/pololu-jrk-g2-software/build/gui/gui_autogen/WTNNEUUVOU/../../../../gui/qt/main_window.h:3,
                 from …/pololu-jrk-g2-software/build/gui/gui_autogen/WTNNEUUVOU/../../../../gui/qt/feedback_wizard.h:6,
                 from …/pololu-jrk-g2-software/build/gui/gui_autogen/WTNNEUUVOU/moc_feedback_wizard.cpp:10,
                 from …/pololu-jrk-g2-software/build/gui/gui_autogen/mocs_compilation.cpp:4:
…/pololu-jrk-g2-software/build/gui/gui_autogen/WTNNEUUVOU/../../../../gui/qt/qcustomplot.h:2378:16: error: field 'mCustomPath' has incomplete type 'QPainterPath'
 2378 |   QPainterPath mCustomPath;
      |                ^~~~~~~~~~~